# Generated by Django 3.1 on 2020-09-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sportsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsection',
            name='img',
            field=models.FileField(default=1, upload_to='sections', verbose_name='Картинка секции'),
            preserve_default=False,
        ),
    ]
