# Generated by Django 3.1 on 2020-09-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sportsection_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsection',
            name='icon',
        ),
    ]
