# Generated by Django 3.1 on 2020-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_sportsection_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО тренера')),
                ('rank', models.CharField(max_length=255, verbose_name='Позиция главного тренера')),
                ('section', models.CharField(choices=[('taekwondo', 'Тхэквондо'), ('grappling', 'Грепплинг'), ('combat', 'Рукопашный бой'), ('gymnastic', 'Художественная гимнастика'), ('brain', 'Секция МОЗГ')], max_length=50, verbose_name='Спортивная секция')),
                ('photo', models.ImageField(upload_to='coach_photos', verbose_name='Фотография тренера')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
    ]
