# Generated by Django 3.1 on 2020-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200922_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsection',
            name='invoice',
            field=models.IntegerField(default=3000, verbose_name='Сумма месячной оплаты'),
        ),
        migrations.AddField(
            model_name='sportsection',
            name='section_tag',
            field=models.CharField(default=1, max_length=50, verbose_name='Таг отображения'),
            preserve_default=False,
        ),
    ]
